name: Lint

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main, master, trunk]

  push:
    branches: [main, master, trunk]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Lint
        run: python3 ./lint/sentence_newline.py ./docs
